name: "solarman-mqtt"
description: "Add-on for solarman-mqtt"
version: "1.0.1"
slug: "solarman-mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
options:
  test_toggle: true
schema:
  test_toggle: bool
